import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/custom_components/navbar/page";
import Footer from "@/custom_components/footer/page";
import ContextData from "./contextapi/contextData";
import Enquiry from "@/custom_components/Enquiry/Enquiry";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Crown Engineering Works",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body  className={`relative ${montserrat.className}`}>
          <Navbar />
         <Enquiry/>
          {children}
          <div className="fixed ml-8 px-2 py-2 shadow-xl bg-offwhite bottom-8">
          <p >ICON</p>
          </div>
          <Footer />
         
      </body>
    </html>
  );
}
